# Software Name
PROGRAM = gnp.elf

# Compiler
CC = /opt/bittboy-toolchain/bin/arm-linux-gcc

# Linker
LDFLAGS = -lc -lgcc -lSDL_mixer -lasound -lmikmod -lmpg123 -lvorbisidec -logg -lSDL -lm -lSDL_image -ljpeg -lpng -lstdc++ -flto -s
CFLAGS = -Ofast -fdata-sections -ffunction-sections -fno-PIC -Wall -flto -DGCW0
CFLAGS += -DSDL_AVAILABLE

# Include
INCLUDES := 

CFLAGS +=  -Isrc
CFILES  = src/ram.c
CFILES += src/refresh.c
CFILES += src/function.c
CFILES += src/dconv.c
CFILES += src/scene.c
CFILES += src/title.c
CFILES += src/init.c
CFILES += src/act.c
CFILES += src/option.c
CFILES += src/ending.c
CFILES += src/logo.c
CFILES += src/audio/generic/audio_sdl.c
CFILES += src/renderer/sdl12generic/renderer_sdl12.c
CFILES += src/input/generic/input_generic.c
CFILES += src/filesystem/gcw0/filesystem_gcw0.c
CFILES += src/platform/generic/platform_generic.c

SYSROOT = $(shell $(CC) --print-sysroot)
CFLAGS += `$(SYSROOT)/usr/bin/sdl-config --cflags`

#
#========================================(Compile)
#

OFILES = $(SFILES:.S=.o) $(CFILES:.c=.o)

$(PROGRAM):	$(OFILES)
			$(CC) $(CFLAGS) $(OFILES) -o $@ $(LDFLAGS)

all: $(PROGRAM)

%.o: %.c
	 $(CC) $(ALL_INCLUDES) $(CFLAGS) -c $< -o $@

clean:
	 -rm -f $(OFILES) $(MAPFILE) $(PROGRAM)
