CC = /opt/gcw0-toolchain/usr/bin/mipsel-linux-gcc
CFLAGS  = -O1 -fdata-sections -ffunction-sections -flto -fomit-frame-pointer -DGCW0 -DSDL_JOYSTICK
CFLAGS += -DSDL_AVAILABLE -Isrc
LDFLAGS =  -nodefaultlibs -lc -lgcc -lm -lSDL_mixer -lmikmod -lmpg123 -lvorbisidec -logg -lSDL -lasound -Wl,-z,norelro -Wl,--hash-style=gnu -Wl,--build-id=none -Wl,-O1,--sort-common,--as-needed,--gc-sections -flto -no-pie -s
SYSROOT = $(shell $(CC) --print-sysroot)
CFLAGS += `$(SYSROOT)/usr/bin/sdl-config --cflags`
OUTPUT = gnp.elf

OBJS  = src/ram.o
OBJS += src/refresh.o
OBJS += src/function.o
OBJS += src/dconv.o
OBJS += src/scene.o
OBJS += src/title.o
OBJS += src/init.o
OBJS += src/act.o
OBJS += src/option.o
OBJS += src/ending.o
OBJS += src/logo.o
OBJS += src/audio/generic/audio_sdl.o
OBJS += src/renderer/sdl12generic/renderer_sdl12.o
OBJS += src/input/generic/input_generic.o
OBJS += src/filesystem/gcw0/filesystem_gcw0.o
OBJS += src/platform/generic/platform_generic.o
SOURCES = $(patsubst %.o, %.c, $(OBJS))

all: $(OUTPUT)

$(OUTPUT): $(OBJS)
	$(CC) $(CFLAGS) -o $@ $(OBJS) $(LDFLAGS)

clean:
	rm $(OBJS)
