CC = i686-w64-mingw32-gcc
CFLAGS  = -Os -fomit-frame-pointer -I./src/gfx -DMINGW -DBUILD_DLL
LDFLAGS = -lmingw32 -lSDLmain -lSDL -lSDL_mixer -mwindows
SYSROOT = $(shell $(CC) --print-sysroot)
CFLAGS += `$(SYSROOT)/bin/sdl-config --cflags`

OBJS  = src/ram.o src/util_snd.o src/function.o src/dconv.o src/scene.o src/title.o src/init.o src/act.o src/option.o src/ending.o src/logo.o
OBJS += src/renderer/sdl12generic/renderer_sdl12.o
OBJS += src/input/generic/input_generic.o
OBJS += src/filesystem/mingw/filesystem_mingw.o
SOURCES = $(patsubst %.o, %.c, $(OBJS))

OUTPUT= gnp.exe

all: $(OUTPUT)

$(OUTPUT): $(OBJS)
	$(CC) -o $@ $(OBJS) $(LDFLAGS)

clean:
	rm $(OBJS)
