# Compatibility wrapper.  The old Emscripten Makefile referenced removed SDL 1.2-era files.
# Use the maintained Canvas/Emscripten backend instead.

all:
	$(MAKE) -f Makefile.wasm-emcc all

serve:
	$(MAKE) -f Makefile.wasm-emcc serve

clean:
	$(MAKE) -f Makefile.wasm-emcc clean

%:
	$(MAKE) -f Makefile.wasm-emcc $@

.PHONY: all serve clean
