# for MacOSX
# need SDL.framework , SDL_mixer.framework , SDL-devel-extra

CC = gcc
CXX = g++
RM  = rm -f
FRAMEWORKS = /Library/Frameworks
DEFAULT_CFLAGS = -Wall -O2 -ffast-math -I$(FRAMEWORKS)/SDL.framework/Headers/ -I$(FRAMEWORKS)/SDL_mixer.framework/Headers/
CFLAGS  = $(DEFAULT_CFLAGS)
CFLAGS += -DSDL_AVAILABLE -Isrc
CXXFLAGS = $(DEFAULT_CFLAGS)
LDFLAGS = -Wl,-framework,SDL -Wl,-framework,SDL_mixer -Wl,-framework,Cocoa

SDLMAIN_SRC=NIBless/SDLMain.m
SDLMAIN_OBJ=NIBless/SDLMain.o

OBJS  = src/ram.o
OBJS += src/refresh.o
OBJS += src/function.o
OBJS += src/dconv.o
OBJS += src/scene.o
OBJS += src/title.o
OBJS += src/init.o
OBJS += src/act.o
OBJS += src/option.o
OBJS += src/ending.o
OBJS += src/logo.o
OBJS += src/audio/generic/audio_sdl.o
OBJS += src/renderer/sdl12generic/renderer_sdl12.o
OBJS += src/input/generic/input_generic.o
OBJS += src/filesystem/generic/filesystem_generic.o
OBJS += src/platform/generic/platform_generic.o

SOURCES = $(patsubst %.o, %.c, $(OBJS))

all: gnp
do-it-all: all

ifeq ($(wildcard .depend),.depend)
include .depend
endif

.PHONY: depend
depend: $(OBJS)
	$(CC) -MM $(CFLAGS) $(SOURCES) > .depend

.PHONY: clean
clean:
	$(RM) $(OBJS) $(SDLMAIN_OBJ) *~ .depend gnp

$(SDLMAIN_OBJ): $(SDLMAIN_SRC)
	gcc -I$(FRAMEWORKS)/SDL.framework/Headers -c $< -o $@

gnp: $(OBJS) $(SDLMAIN_OBJ)
	$(CXX) -o $@ $(OBJS) $(LDFLAGS) $(SDLMAIN_OBJ)
