TARGET = GannatsuPortable
OBJS  = src/ram.o
OBJS += src/refresh.o
OBJS += src/function.o
OBJS += src/dconv.o
OBJS += src/scene.o
OBJS += src/title.o
OBJS += src/init.o
OBJS += src/act.o
OBJS += src/option.o
OBJS += src/ending.o
OBJS += src/logo.o
OBJS += src/audio/generic/audio_sdl.o
OBJS += src/renderer/sdl12generic/renderer_sdl12.o
OBJS += src/input/generic/input_generic.o
OBJS += src/filesystem/generic/filesystem_generic.o
OBJS += src/platform/psp/platform_psp.o

BUILD_PRX = 1
PSP_FW_VERSION = 390

CFLAGS = -O2 -G0 -Wall -w -g -Wextra -DPSPUMODE
CFLAGS += -DSDL_AVAILABLE -Isrc
CXXFLAGS = $(CFLAGS) -fno-exceptions -fno-rtti -fno-builtin-printf
ASFLAGS = $(CFLAGS)

LIBDIR =
LIBS = -L/usr/local/pspsdk/lib
LDFLAGS =

EXTRA_TARGETS = EBOOT.PBP
PSP_EBOOT_TITLE = Gannatsu Portable PSP
PSP_EBOOT_ICON = ICON0.png

PSPSDK=$(shell psp-config --pspsdk-path)
PSPBIN = $(PSPSDK)/../bin
CFLAGS += -I/usr/local/pspdev/psp/include/SDL
LIBS += $(shell $(PSPBIN)/freetype-config --libs)
LIBS += -lSDL_mixer
LIBS += /usr/local/pspdev/psp/lib/libvorbisidec.a /usr/local/pspdev/psp/lib/libvorbis.a /usr/local/pspdev/psp/lib/libogg.a
LIBS += -L/usr/local/pspdev/psp/lib -lSDL -lSDL_gfx -lm -L/usr/local/pspdev/psp/sdk/lib -lpspdebug -lpspgu -lpspctrl -lpspge -lpspdisplay -lpsphprm -lpspsdk -lpsprtc -lpspaudio -lc -lpspuser -lpsputility -lpspkernel -lpspnet_inet
LIBS += -lSDL_ttf -lfreetype
LIBS += -lpng -ljpeg -lz -lm -lpsppower -lmad -lpspaudio -lpspaudiolib
include $(PSPSDK)/lib/build.mak
