CC = kos-cc
SH_DIRECTORY=/opt/toolchains/dc/sh-elf/bin/

CFLAGS  = -Ofast -flto -Wall -Wextra -DDREAMCAST -DNAOMI
CFLAGS += -DSDL_AVAILABLE -Isrc
CXXFLAGS = $(CFLAGS)
LDFLAGS = -lc -lm -lSDL_naomi -lz -s -flto

#CFLAGS  += -DOPUS_MUSIC
#LDFLAGS += -lopusplay -lopusfile -logg -lopus

CFLAGS  += -DADX_PLAY
LDFLAGS += -lADX

CFLAGS +=  -ml -m4-single-only -Wl,-Ttext=0x8c020000 -Wl,--gc-sections -nodefaultlibs -L/opt/toolchains/dc/kos/lib/dreamcast -L/opt/toolchains/dc/kos/addons/lib/dreamcast -L/opt/toolchains/dc/kos/../kos-ports/lib -DNAOMI

SYSROOT = $(shell $(CC) --print-sysroot)
CFLAGS += `$(SYSROOT)/bin/sdl-config --cflags`

OBJS  = romdisk.o
OBJS += src/ram.o
OBJS += src/refresh.o
OBJS += src/function.o
OBJS += src/dconv.o
OBJS += src/scene.o
OBJS += src/title.o
OBJS += src/init.o
OBJS += src/act.o
OBJS += src/option.o
OBJS += src/ending.o
OBJS += src/logo.o
OBJS += src/audio/dreamcast/audio_dreamcast.o
OBJS += src/renderer/dreamcast/renderer_dreamcast.o
OBJS += src/input/dreamcast/input_dreamcast.o
OBJS += src/filesystem/dreamcast/filesystem_dreamcast.o
OBJS += src/filesystem/dreamcast/vmu.o
OBJS += src/platform/dreamcast/platform_dreamcast.o
SOURCES = $(patsubst %.o, %.c, $(OBJS))

all: gnp

romdisk.img:
	$(KOS_GENROMFS) -f romdisk.img -d ./rd -v

romdisk.o: romdisk.img
	$(KOS_BASE)/utils/bin2o/bin2o romdisk.img romdisk romdisk.o

gnp: $(OBJS)
	$(CC) $(CFLAGS) -o $@ $(OBJS) $(LDFLAGS)
	naomibintool build GNP_NAOMI.BIN -d "Gameblabla" -e $@

clean:
	rm $(OBJS) *.img
