# Software Name
PROGRAM = gnp.elf

# Compiler
CC = /opt/rs97-toolchain/bin/mipsel-linux-gcc
LDFLAGS =  -nodefaultlibs -lc -lgcc -lSDL -lSDL_mixer -lmpg123 -lmikmod -lvorbisidec -logg  -no-pie -Wl,--as-needed -Wl,--gc-sections -flto -s
CFLAGS = -Ofast -fdata-sections -ffunction-sections -mno-fp-exceptions -mno-check-zero-division -mframe-header-opt -fsingle-precision-constant -fno-common -mips32 -mno-mips16 -fno-PIC -mno-abicalls -flto
CFLAGS += -DSDL_AVAILABLE
CFLAGS	+= -DGCW
SYSROOT = $(shell $(CC) --print-sysroot)
CFLAGS += `$(SYSROOT)/usr/bin/sdl-config --cflags`

# Include
INCLUDES := 

CFLAGS +=  -Isrc
CFILES  = src/ram.c
CFILES += src/refresh.c
CFILES += src/function.c
CFILES += src/dconv.c
CFILES += src/scene.c
CFILES += src/title.c
CFILES += src/init.c
CFILES += src/act.c
CFILES += src/option.c
CFILES += src/ending.c
CFILES += src/logo.c
CFILES += src/audio/generic/audio_sdl.c
CFILES += src/renderer/sdl12generic/renderer_sdl12.c
CFILES += src/input/generic/input_generic.c
CFILES += src/filesystem/gcw0/filesystem_gcw0.c
CFILES += src/platform/generic/platform_generic.c

#
#========================================(Compile)
#

OFILES = $(SFILES:.S=.o) $(CFILES:.c=.o)

$(PROGRAM):	$(OFILES)
			$(CC) $(CFLAGS) $(OFILES) -o $@ $(LDFLAGS)

all: $(PROGRAM)

%.o: %.c
	 $(CC) $(ALL_INCLUDES) $(CFLAGS) -c $< -o $@

clean:
	 -rm -f $(OFILES) $(MAPFILE) $(PROGRAM)
