CC = kos-cc
SH_DIRECTORY=/opt/toolchains/dc/sh-elf/bin/

CFLAGS  = -Ofast -flto -Wall -Wextra -DDREAMCAST
CFLAGS += -DSDL_AVAILABLE -Isrc
CXXFLAGS = $(CFLAGS)
LDFLAGS = -lc -lm -lSDL -lz -s -flto

#CFLAGS  += -DOPUS_MUSIC
#LDFLAGS += -lopusplay -lopusfile -logg -lopus

CFLAGS  += -DADX_PLAY
LDFLAGS += -lADX

SYSROOT = $(shell $(CC) --print-sysroot)
CFLAGS += `$(SYSROOT)/bin/sdl-config --cflags`

OBJS  = romdisk.o
OBJS += src/ram.o
OBJS += src/refresh.o
OBJS += src/function.o
OBJS += src/dconv.o
OBJS += src/scene.o
OBJS += src/title.o
OBJS += src/init.o
OBJS += src/act.o
OBJS += src/option.o
OBJS += src/ending.o
OBJS += src/logo.o
OBJS += src/audio/dreamcast/audio_dreamcast.o
OBJS += src/renderer/dreamcast/renderer_dreamcast.o
OBJS += src/input/dreamcast/input_dreamcast.o
OBJS += src/filesystem/dreamcast/filesystem_dreamcast.o
OBJS += src/filesystem/dreamcast/vmu.o
OBJS += src/platform/dreamcast/platform_dreamcast.o
SOURCES = $(patsubst %.o, %.c, $(OBJS))

all: gnp

#CDDA but due to issues, it's commented out
#pack:
#	rm -f IP.BIN
#	sh-elf-objcopy -R .stack -O binary gnp main.bin
#	${KOS_BASE}/utils/scramble/scramble main.bin ./cd/1ST_READ.BIN
#	makeip ip.txt IP.BIN
#	mkisofs -C 0,$(shell lbacalc track01.raw track02.raw track03.raw track04.raw track05.raw track06.raw track07.raw) -V GANBARE -G IP.BIN -joliet -rock -l -o "ganbare.iso" ./cd
#	mds4dc -c ganbare.mds ganbare.iso track01.raw track02.raw track03.raw track04.raw track05.raw track06.raw track07.raw

pack:
	rm -f IP.BIN
	sh-elf-objcopy -R .stack -O binary gnp main.bin
	${KOS_BASE}/utils/scramble/scramble main.bin ./cd/1ST_READ.BIN
	makeip ip.txt IP.BIN
	mkisofs -V GANBARE -G IP.BIN -joliet -rock -l -x cd -o "ganbare.iso" ./cd
	cdi4dc ganbare.iso ganbare.cdi -d

romdisk.img:
	rm -f IP.BIN
	rm -f -r ./rd
	rm -f -r ./cd/image
	mkdir -p ./rd
	mkdir -p ./rd/image
	mkdir -p ./rd/image/map
	cp -r ./data/4by3/image/map ./rd/image/
	cp -r ./data/data ./rd/
	cp -r ./data/4by3/image ./cd/
	$(KOS_GENROMFS) -f romdisk.img -d ./rd -v

romdisk.o: romdisk.img
	$(KOS_BASE)/utils/bin2o/bin2o romdisk.img romdisk romdisk.o

gnp: $(OBJS)
	$(CC) $(CFLAGS) -o $@ $(OBJS) $(LDFLAGS)

clean:
	rm $(OBJS) *.cdi *.iso *.BIN ./gnp romdisk.img
	rm -f IP.BIN
	rm -f -r ./rd
	rm -f -r ./cd/image
