CC = i686-w64-mingw32-gcc
CFLAGS  = -Os -fomit-frame-pointer -I./src/gfx -DMINGW -DBUILD_DLL
CFLAGS += -DSDL_AVAILABLE -Isrc
LDFLAGS = -lmingw32 -lSDLmain -lSDL -lSDL_mixer -mwindows
SYSROOT = $(shell $(CC) --print-sysroot)
CFLAGS += `$(SYSROOT)/bin/sdl-config --cflags`

OBJS  = src/ram.o
OBJS += src/refresh.o
OBJS += src/function.o
OBJS += src/dconv.o
OBJS += src/scene.o
OBJS += src/title.o
OBJS += src/init.o
OBJS += src/act.o
OBJS += src/option.o
OBJS += src/ending.o
OBJS += src/logo.o
OBJS += src/audio/generic/audio_sdl.o
OBJS += src/renderer/sdl12generic/renderer_sdl12.o
OBJS += src/input/generic/input_generic.o
OBJS += src/filesystem/mingw/filesystem_mingw.o
OBJS += src/platform/generic/platform_generic.o
SOURCES = $(patsubst %.o, %.c, $(OBJS))

OUTPUT= gnp.exe

all: $(OUTPUT)

$(OUTPUT): $(OBJS)
	$(CC) -o $@ $(OBJS) $(LDFLAGS)

clean:
	rm $(OBJS)
