#!/bin/sh

mkdir -p ipkg/home/retrofw/games/gnp
mkdir -p ipkg/home/retrofw/games/gnp/data
mkdir -p ipkg/home/retrofw/games/gnp/image
mkdir -p ipkg/home/retrofw/games/gnp/sound
mkdir -p ipkg/home/retrofw/apps/gmenu2x/sections/games
cp gnp ipkg/home/retrofw/games/gnp/gnp
cp opk/icon.png ipkg/home/retrofw/games/gnp/gnp.png
cp COPYRIGHT ipkg/home/retrofw/games/gnp/COPYRIGHT
cp -r opk/data ipkg/home/retrofw/games/gnp
cp -r opk/image ipkg/home/retrofw/games/gnp
cp -r opk/sound ipkg/home/retrofw/games/gnp

cd ipkg

# https://unix.stackexchange.com/questions/219268/how-to-add-new-lines-when-using-echo
print()
	case    ${IFS- } in
	(\ *)   printf  %b\\n "$*";;
	(*)     IFS=\ $IFS
	printf  %b\\n "$*"
	IFS=${IFS#?}
esac

# Create GmenuNx entry file plus other things

print 'Package: gnp
Version: 20190207
Description: Ganbare Natsuki-San
Section: games
Priority: optional
Maintainer: gameblabla
Architecture: mipsel
Homepage: https://github.com/gameblabla/Ganbare-Natsuki-San
Depends:
Source: https://github.com/gameblabla/Ganbare-Natsuki-San' > control

print '2.0' > debian-binary

print 'title=Ganbare
description=Ganbare Natsuki-San
exec=/home/retrofw/games/gnp/gnp' > home/retrofw/apps/gmenu2x/sections/games/gnp

tar -czvf control.tar.gz control --owner=0 --group=0
tar -czvf data.tar.gz home --owner=0 --group=0
ar rv ../gnp.ipk control.tar.gz data.tar.gz debian-binary

cd ..
rm -r ipkg
