#!/bin/sh

mkdir -p opk
cp ./gnp.elf opk/gnp.elf
cp ./data/assets/gnp.png opk/icon.png
cp -r ./data/data opk/
cp -r ./data/"$2"/image opk/
cp -r ./data/sound opk/

# https://unix.stackexchange.com/questions/219268/how-to-add-new-lines-when-using-echo
print()
	case    ${IFS- } in
	(\ *)   printf  %b\\n "$*";;
	(*)     IFS=\ $IFS
	printf  %b\\n "$*"
	IFS=${IFS#?}
esac

# Create GmenuNx entry file plus other things

print '[Desktop Entry]
Type=Application
Name=Ganbare
Comment=Puzzle/Platform game
Exec=gnp.elf
Icon=icon
Terminal=false
Type=Application
Categories=games;
X-OD-NeedsDownscaling=true' > opk/default."$1".desktop

mksquashfs ./opk gnp_"$1".opk -all-root -noappend -no-exports -no-xattrs

rm -r opk
